services:
  _defaults:
    autowire: true

  ICanBoogie\ActiveRecord\Config:
    factory: [ '@ICanBoogie\ConfigProvider', config_for_class ]
    arguments:
    - ICanBoogie\ActiveRecord\Config

  ICanBoogie\ActiveRecord\ConnectionProvider:
    class: ICanBoogie\ActiveRecord\ConnectionCollection
    factory: [ ICanBoogie\Binding\ActiveRecord\Factory, build_connections ]
    public: true # required by $app->connections

  ICanBoogie\ActiveRecord\ModelCollection:
    factory: [ ICanBoogie\Binding\ActiveRecord\Factory, build_models ]

  ICanBoogie\ActiveRecord\ModelProvider:
    alias: ICanBoogie\ActiveRecord\ModelCollection
    public: true # required by StaticModelProvider

  ICanBoogie\ActiveRecord\ModelIterator:
    alias: ICanBoogie\ActiveRecord\ModelCollection

  # Console

  ICanBoogie\Binding\ActiveRecord\Console\ListRecordsCommand:
    class: ICanBoogie\Binding\ActiveRecord\Console\ListRecordsCommand
    arguments:
      $style: '%console.style.table%'
    tags: [ console.command ]

  ICanBoogie\Binding\ActiveRecord\Console\ListConnectionsCommand:
    class: ICanBoogie\Binding\ActiveRecord\Console\ListConnectionsCommand
    arguments:
      $style: '%console.style.table%'
    tags: [ console.command ]

  ICanBoogie\Binding\ActiveRecord\Console\InstallCommand:
    class: ICanBoogie\Binding\ActiveRecord\Console\InstallCommand
    arguments:
      $style: '%console.style.table%'
    tags: [ console.command ]
