# yaml-language-server: $schema=../vendor/symfony/dependency-injection/Loader/schema/services.schema.json
services:
  _defaults:
    autowire: true

  ICanBoogie\ActiveRecord\Config:
    factory: [ '@ICanBoogie\ConfigProvider', config_for_class ]
    arguments:
    - ICanBoogie\ActiveRecord\Config

  ICanBoogie\ActiveRecord\ConnectionProvider:
    class: ICanBoogie\ActiveRecord\ConnectionRegistry
    factory: [ ICanBoogie\Binding\ActiveRecord\Factory, build_connections ]

  ICanBoogie\ActiveRecord\ModelRegistry:
    factory: [ ICanBoogie\Binding\ActiveRecord\Factory, build_models ]

  ICanBoogie\ActiveRecord\ModelProvider:
    alias: ICanBoogie\ActiveRecord\ModelRegistry
    public: true # required by StaticModelProvider

  ICanBoogie\ActiveRecord\ModelIterator:
    alias: ICanBoogie\ActiveRecord\ModelRegistry

  ICanBoogie\ActiveRecord\ModelInstaller: ~

  # Console

  ICanBoogie\Binding\ActiveRecord\Console\ListRecordsCommand:
    class: ICanBoogie\Binding\ActiveRecord\Console\ListRecordsCommand
    arguments:
      $style: '%console.style.table%'
    tags: [ console.command ]

  ICanBoogie\Binding\ActiveRecord\Console\ListConnectionsCommand:
    class: ICanBoogie\Binding\ActiveRecord\Console\ListConnectionsCommand
    arguments:
      $style: '%console.style.table%'
    tags: [ console.command ]

  ICanBoogie\Binding\ActiveRecord\Console\InstallCommand:
    class: ICanBoogie\Binding\ActiveRecord\Console\InstallCommand
    arguments:
      $style: '%console.style.table%'
    tags: [ console.command ]
