services:
  _defaults:
    autowire: true

  ICanBoogie\ActiveRecord\Config:
    factory: [ '@ICanBoogie\ConfigProvider', config_for_class ]
    arguments:
    - ICanBoogie\ActiveRecord\Config

  ICanBoogie\ActiveRecord\ConnectionProvider:
    class: ICanBoogie\ActiveRecord\ConnectionCollection
    factory: [ ICanBoogie\Binding\ActiveRecord\Factory, build_connections ]
    public: true # required by $app->connections

  ICanBoogie\ActiveRecord\ModelCollection:
    factory: [ ICanBoogie\Binding\ActiveRecord\Factory, build_models ]

  ICanBoogie\ActiveRecord\ModelProvider:
    alias: ICanBoogie\ActiveRecord\ModelCollection
    public: true # required by StaticModelProvider

  ICanBoogie\ActiveRecord\ModelIterator:
    alias: ICanBoogie\ActiveRecord\ModelCollection

  ICanBoogie\ActiveRecord\ModelResolver:
    alias: ICanBoogie\ActiveRecord\ModelCollection
    public: true # required by StaticModelResolver

  # Console

  console.command.activerecord.models.list:
    class: ICanBoogie\Binding\ActiveRecord\Console\ListModelsCommand
    arguments:
      $style: '%console.style.table%'
    tags:
    - { name: console.command, command: 'activerecord:models' }
    - { name: console.command, command: 'activerecord:models:list' }

  console.command.activerecord.connections.list:
    class: ICanBoogie\Binding\ActiveRecord\Console\ListConnectionsCommand
    arguments:
      $style: '%console.style.table%'
    tags:
    - { name: console.command, command: 'activerecord:connections' }
    - { name: console.command, command: 'activerecord:connections:list' }

  console.command.activerecord.install:
    class: ICanBoogie\Binding\ActiveRecord\Console\InstallCommand
    tags:
    - { name: console.command, command: 'activerecord:install' }
