services:
  _defaults:
    autowire: true

  ICanBoogie\ActiveRecord\ConnectionProvider:
    class: ICanBoogie\ActiveRecord\ConnectionCollection
    factory: [ ICanBoogie\Binding\ActiveRecord\Hooks, app_get_connections ]

  ICanBoogie\ActiveRecord\ModelProvider:
    class: ICanBoogie\ActiveRecord\ModelCollection
    factory: [ ICanBoogie\Binding\ActiveRecord\Hooks, app_get_models ]
